//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1 {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class libai {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal libai() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.libai", typeof(libai).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Visual Studio 2017 常用快捷键
        ///1、窗口快捷键
        ///复制代码
        /// 1 Ctrl+W,W: 浏览器窗口
        /// 2 Ctrl+W,S: 解决方案管理器 （Solution）
        /// 3 Ctrl+W,C: 类视图 （Class）
        /// 4 Ctrl+W,E: 错误列表 （Error）
        /// 5 Ctrl+W,O: 输出窗口（Output）
        /// 6 Ctrl+W,P: 属性窗口 （Property）
        /// 7 Ctrl+W,T: 任务列表 （Task）
        /// 8 Ctrl+W,X: 工具箱 （Tool,t已被任务列表占用）
        /// 9 Ctrl+W,B: 书签窗口 （Bookmark,方便寻找代码）
        ///10 Ctrl+W,U: 文档大纲 （OutLine；第二个字母U）
        ///11 Ctrl+D,B: 断点窗口 （breakpoint）
        ///12 Ctrl+D,I: 即时窗口 （immediately）
        ///复制代码
        ///2、项目功能快捷键
        ///复制代码
        /// 1 CTRL+TAB：活动窗体切换 （alt+tab：任务切换）
        /// 2 CTRL+SHIFT+TAB：上一个文档窗口
        /// 3 F7: 查看代码 （WebForm：查看后 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Visual_Studio_2017_常用快捷键 {
            get {
                return ResourceManager.GetString("Visual_Studio_2017_常用快捷键", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string 人生 {
            get {
                return ResourceManager.GetString("人生", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string 白马 {
            get {
                return ResourceManager.GetString("白马", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://127.0.0.1:8080/weilai/sql/bselectdb.jsp 的本地化字符串。
        /// </summary>
        internal static string 黑色 {
            get {
                return ResourceManager.GetString("黑色", resourceCulture);
            }
        }
    }
}
